# Generated by Django 3.0.3 on 2020-05-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='teacher',
        ),
        migrations.AddField(
            model_name='profile',
            name='group',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
