# Generated by Django 3.0.3 on 2020-08-10 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200810_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiniSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MethodicalInstructionsGlobal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('mini_subject', models.ManyToManyField(to='app.MiniSubject')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='methodical_instructions',
            field=models.ManyToManyField(to='app.MethodicalInstructionsGlobal'),
        ),
    ]
