# Generated by Django 2.2 on 2020-05-20 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_course_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='picture',
        ),
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
