# Generated by Django 3.0.3 on 2020-05-20 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200520_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(upload_to='media/%Y/%m/%d'),
        ),
    ]
