# Generated by Django 3.0.3 on 2020-07-16 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_lesson_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(default=1, upload_to='media/course'),
            preserve_default=False,
        ),
    ]
