# Generated by Django 3.0.3 on 2020-07-18 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20200718_2357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='data',
            new_name='date',
        ),
    ]
