# Generated by Django 3.0.3 on 2020-07-19 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20200719_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupidtask',
            name='task_id',
        ),
        migrations.AddField(
            model_name='groupidtask',
            name='task_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Task'),
        ),
    ]
