# Generated by Django 3.0.3 on 2020-07-19 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20200719_1702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskgroup',
            old_name='task_id',
            new_name='tasks',
        ),
    ]
