# Generated by Django 3.0.3 on 2020-07-19 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20200719_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskgroup',
            name='local',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
