# Generated by Django 3.0.3 on 2020-07-19 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_taskgroup_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='file',
            field=models.NullBooleanField(),
        ),
    ]
