# Generated by Django 3.0.3 on 2020-07-20 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_task_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='char_format_flag',
        ),
        migrations.RemoveField(
            model_name='task',
            name='programmin_format_flag',
        ),
        migrations.RemoveField(
            model_name='task',
            name='string_format_flag',
        ),
        migrations.AddField(
            model_name='task',
            name='format_flag',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
