# Generated by Django 3.0.3 on 2020-07-21 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20200720_0425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskanswers',
            name='accuracy',
            field=models.BooleanField(default=1),
        ),
    ]
