# Generated by Django 3.0.3 on 2020-07-21 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20200721_0317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskanswers',
            name='accuracy',
        ),
        migrations.AddField(
            model_name='task',
            name='accuracy',
            field=models.BooleanField(default=1),
        ),
        migrations.AlterField(
            model_name='task',
            name='revizion_format_flag',
            field=models.BooleanField(default=0),
        ),
    ]
