# Generated by Django 3.0.3 on 2020-07-22 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20200721_0320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskanswers',
            name='task_id',
        ),
        migrations.AddField(
            model_name='task',
            name='answers',
            field=models.ManyToManyField(to='app.TaskAnswers'),
        ),
    ]
