# Generated by Django 3.0.3 on 2020-07-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20200722_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='revizion_format_flag',
            field=models.BooleanField(default=1),
        ),
    ]
