# Generated by Django 3.0.3 on 2020-07-22 18:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0029_auto_20200722_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='correct_answer',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
